spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.253.65:3306/ssm_crud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: uAiqwVwjJ8-i
mybatis:
  mapper-locations: classpath:mapper/*.xml