package com.xie.springbootdao.dao;

import com.xie.springbootdao.model.TblDept;
import com.xie.springbootdao.model.TblDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    long countByExample(TblDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int deleteByExample(TblDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int insert(TblDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int insertSelective(TblDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    List<TblDept> selectByExample(TblDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    TblDept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TblDept record, @Param("example") TblDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TblDept record, @Param("example") TblDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblDept record);
}